name: FlutterWidgets
description: To Learn Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: huawenxingkai
      fonts:
        - asset: fonts/华文行楷.ttf
    - family: fangzhengjianti
      fonts:
        - asset: fonts/方正简体.ttf